services:
  web:
    build: .
    container_name: fastapi-app
    volumes:
      - .:/app
    networks:
      - web-gateway
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi-app.rule=Host(`fastapi-app.localhost`)"
      - "traefik.http.routers.fastapi-app.entrypoints=websecure"
      - "traefik.http.routers.fastapi-app.tls=true"
      # Tell Traefik to route to port 8000 inside container
      - "traefik.http.services.fastapi-app.loadbalancer.server.port=8000"

networks:
  web-gateway:
    external: true
