tls:
  certificates:
    - certFile: /etc/traefik/certs/traefik.localhost.pem
      keyFile: /etc/traefik/certs/traefik.localhost-key.pem
    - certFile: /etc/traefik/certs/portainer.localhost.pem
      keyFile: /etc/traefik/certs/portainer.localhost-key.pem
    - certFile: /etc/traefik/certs/mailhog.localhost.pem
      keyFile: /etc/traefik/certs/mailhog.localhost-key.pem
    - certFile: /etc/traefik/certs/adminer.localhost.pem
      keyFile: /etc/traefik/certs/adminer.localhost-key.pem
    - certFile: /etc/traefik/certs/grafana.localhost.pem
      keyFile: /etc/traefik/certs/grafana.localhost-key.pem
    - certFile: /etc/traefik/certs/metrics.localhost.pem
      keyFile: /etc/traefik/certs/metrics.localhost-key.pem
    - certFile: /etc/traefik/certs/whoami.localhost.pem
      keyFile: /etc/traefik/certs/whoami.localhost-key.pem
